### In this RMD I am calculating a multiple linear regression to predict hydrologic signatures and flow regimes

###load libraries
```{r}
library(tidyverse)
# install.packages("olsrr")
library(olsrr)
library(ggplot2)
library(Hmisc)
library(patchwork)

```

### load in data
```{r}
forMR <- read_csv("WSfactorsLarge.csv")

head(forMR)
```
###Correlation matrix
```{r}
#Test using some of the  top variables across RF runs
MRselect <- forMR %>%
  dplyr::select(HGC, slope_fdc, geol_porostiy, VarB, SANDAVE, HGB, RFACT, geol_permeability, soil_depth_statsgo, ROCKDEPAVE, sand_frac, runoff_ratio, aridity, ELEV_MEDIAN_M_BASIN, PLANTNLCD06, RIP100_DEV)

#correlation matrix
# parameters clean, give to function cor(), give to data frame to get matrix, take out related above .7, iterative and keep going until you don't want to anymore 
cor_matrix <- cor(MRselect)

print(cor_matrix)

```



###Running BFI in a stepwise progression using top variables accross all top importance predictors
```{r}
BFI <- forMR$BFI_AVE

# Check for missing and infinite values in the data
any(is.na(MRselect))

# Fit a linear regression model with the selected predictors
my_model <- lm(BFI ~ ., data = MRselect)

# Fit a stepwise regression model with the selected predictors
BFI_step_model <- step(lm(BFI ~ ., data = MRselect), direction = "both")

# Print the model summary
summary(BFI_step_model)

```

### stepwise linear regression
```{r}
#Create an empty data frame to store model results
model_results <- data.frame()

BFI <- forMR$BFI_AVE

# Check for missing and infinite values in the data
any(is.na(MRselect))

# Fit a linear regression model with the selected predictors
my_model <- lm(BFI ~ ., data = MRselect)

# Fit a stepwise regression model with the selected predictors
BFI_step_model <- step(lm(BFI ~ ., data = MRselect), direction = "both")

# Print the model summary
summary(BFI_step_model)

BFI_step_model$coefficients

BFIactual <- forMR %>%
  dplyr::select(BFI_AVE) %>%
  slice_tail(n = 83)

BFIdf <- data.frame(actual = BFIactual, predicted = predict(BFI_step_model))

BFI <- ggplot(BFIdf, aes(x = BFI_AVE, y = predicted)) +
  geom_point() +
  geom_abline() +
  xlab("Actual BFI") +
  ylab("Predicted BFI") 

```
### RBI
```{r}
#Create an empty data frame to store model results
model_results <- data.frame()

RBI <- forMR$Flashiness

# Check for missing and infinite values in the data
any(is.na(MRselect))

# Fit a linear regression model with the selected predictors
my_model <- lm(RBI ~ ., data = MRselect)

# Fit a stepwise regression model with the selected predictors
RBI_step_model <- step(lm(RBI ~ ., data = MRselect), direction = "both")

# Print the model summary
summary(RBI_step_model)

RBIactual <- forMR %>%
  dplyr::select(Flashiness) %>%
  slice_tail(n = 83)

RBIdf <- data.frame(actual = RBIactual, predicted = predict(RBI_step_model))

RBI <- ggplot(RBIdf, aes(x = Flashiness, y = predicted)) +
  geom_point() +
  geom_abline() +
  xlab("Actual RBI") +
  ylab("Predicted RBI") 
```

###Ninetieth Percentile flow
```{r}
NP <- forMR$NinetiethP

# Check for missing and infinite values in the data
any(is.na(MRselect))

# Fit a linear regression model with the selected predictors
my_model <- lm(NP ~ ., data = MRselect)

# Fit a stepwise regression model with the selected predictors
NP_step_model <- step(lm(NP ~ ., data = MRselect), direction = "both")

# Print the model summary
summary(NP_step_model)

NPactual <- forMR %>%
  dplyr::select(NinetiethP) %>%
  slice_tail(n = 83)

NPdf <- data.frame(actual = NPactual, predicted = predict(NP_step_model))

NinetiethP <- ggplot(NPdf, aes(x = NinetiethP, y = predicted)) +
  geom_point() +
  geom_abline() +
  xlab("Actual Ninetieth Percentile flow") +
  ylab("Predicted Ninetieth Percentile flow")
```

###Tenth Percentile flow
```{r}
TP <- forMR$TenthP

# Check for missing and infinite values in the data
any(is.na(MRselect))

# Fit a linear regression model with the selected predictors
my_model <- lm(TP ~ ., data = MRselect)

# Fit a stepwise regression model with the selected predictors
TP_step_model <- step(lm(TP ~ ., data = MRselect), direction = "both")

# Print the model summary
summary(TP_step_model)

TP_step_model$coefficients

TPactual <- forMR %>%
  dplyr::select(TenthP) %>%
  slice_tail(n = 83)

TPdf <- data.frame(actual = TPactual, predicted = predict(TP_step_model))

TenthP <- ggplot(TPdf, aes(x = TenthP, y = predicted)) +
  geom_point() +
  geom_abline() +
  xlab("Actual Tenth Percentile flow") +
  ylab("Predicted Tenth Percentile flow") 

BFI + RBI + TenthP + NinetiethP

```

