---
title: "Plotting"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basic stats

```{r}
QdvStatsSF <- QdvStats %>% st_as_sf(sf_column_name = "geometry")

#mean
MeanQMap <- tm_shape(QdvStatsSF)+
  tm_symbols(col = "Mean", size = 0.2, style = "quantile", legend.hist = TRUE)+
  tm_layout(legend.outside = TRUE)+
tm_shape(us_states)+
  tm_borders()

#median
MedQMap <- tm_shape(QdvStatsSF)+
  tm_symbols(col = "Median", size = 0.2, style = "quantile", legend.hist = TRUE)+
  tm_layout(legend.outside = TRUE)+
tm_shape(us_states)+
  tm_borders()

#standard deviation
SdQMap <- tm_shape(QdvStatsSF)+
  tm_symbols(col = "StandardDeviation", size = 0.2, style = "quantile", legend.hist = TRUE)+
  tm_layout(legend.outside = TRUE)+
tm_shape(us_states)+
  tm_borders()

#IQR
IqrQMap <- tm_shape(QdvStatsSF)+
  tm_symbols(col = "IQR", size = 0.2, style = "quantile", legend.hist = TRUE)+
  tm_layout(legend.outside = TRUE)+
tm_shape(us_states)+
  tm_borders()

#10th percentile
TenthPQMap <- tm_shape(QdvStatsSF)+
  tm_symbols(col = "TenthP", size = 0.2, style = "quantile", legend.hist = TRUE)+
  tm_layout(legend.outside = TRUE)+
tm_shape(us_states)+
  tm_borders()

#90th percentile
NinetiethPQMap <- tm_shape(QdvStatsSF)+
  tm_symbols(col = "NinetiethP", size = 0.2, style = "quantile", legend.hist = TRUE)+
  tm_layout(legend.outside = TRUE)+
tm_shape(us_states)+
  tm_borders()

MeanQMap
MedQMap
SdQMap
IqrQMap
TenthPQMap
NinetiethPQMap

tmap_save(MeanQMap, "Plots/MeanQMap.jpg")
tmap_save(MedQMap, "Plots/MedianQMap.jpg")
tmap_save(SdQMap, "Plots/SdQMap.jpg")
tmap_save(IqrQMap, "Plots/IqrQMap.jpg")
tmap_save(TenthPQMap, "Plots/TenthPercentQMap.jpg")
tmap_save(NinetiethPQMap, "Plots/NinetiethPecentQMap.jpg")

#QdvStats <- QdvStats %>% full_join(AppGagesSlim, by = c("site_no" = "STAID"))

MeanQBox <- QdvStats %>% ggplot(aes(PROVINCE, Mean))+
  stat_boxplot()+
  ylab("Mean Q (mm/day)")+
  theme(axis.text.x = element_text(angle = 90))

ggsave("Plots/MeanQBoxplot.jpg", MeanQBox)

MedianQBox <- QdvStats %>% ggplot(aes(PROVINCE, Median))+
  stat_boxplot()+
  ylab("Median Q (mm/day)")+
  theme(axis.text.x = element_text(angle = 90))

ggsave("Plots/MedianQBoxplot.jpg", MedianQBox)

SdQBox <- QdvStats %>% ggplot(aes(PROVINCE, StandardDeviation))+
  stat_boxplot()+
  ylab("Q Standard Deviation (mm/day)")+
  theme(axis.text.x = element_text(angle = 90))

ggsave("Plots/sdQBoxplot.jpg", SdQBox)

iqrQBox <- QdvStats %>% ggplot(aes(PROVINCE, IQR))+
  stat_boxplot()+
  ylab("Q IQR (mm/day)")+
  theme(axis.text.x = element_text(angle = 90))

ggsave("Plots/iqrQBoxplot.jpg", iqrQBox)

ninetiethPctQBox <- QdvStats %>% ggplot(aes(PROVINCE, NinetiethP))+
  stat_boxplot()+
  ylab("90th Percentile Q (mm/day)")+
  theme(axis.text.x = element_text(angle = 90))

ggsave("Plots/90thPctQBoxplot.jpg", ninetiethPctQBox)

TenthPctQBox <- QdvStats %>% ggplot(aes(PROVINCE, TenthP))+
  stat_boxplot()+
  ylab("10th Percentile Q (mm/day)")+
  theme(axis.text.x = element_text(angle = 90))

ggsave("Plots/10thPctQBoxplot.jpg", TenthPctQBox)
```

```{r}
WSfactorsLarge <- WSfactorsLarge %>% inner_join(dplyr::select(QdvStats, site_no, Mean, NinetiethP, TenthP), by = c("STAID" = "site_no"))

#Dominant geology
MEANvsGEO <- WSfactorsLarge %>% ggplot(aes(GEOL_REEDBUSH_DOM, Mean))+
  stat_boxplot()+
  ylab("Average Flow (mm/day)")+
  xlab("Dominant Geology")

ggsave("Plots/Mean/MEANvsGEO.jpg", MEANvsGEO)

#topographic wetness index
MEANvsTWI <- WSfactorsLarge %>% ggplot(aes(TOPWET, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("Topographic Wetness Index")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$TOPWET), parse = TRUE)

ggsave("Plots/Mean/MEANvsTWI.jpg", MEANvsTWI)

#average annual precip
MEANvsP <- WSfactorsLarge %>% ggplot(aes(PPTAVG_BASIN, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("Average Annual Precipitation, cm")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$PPTAVG_BASIN), parse = TRUE)

ggsave("Plots/Mean/MEANvsP.jpg", MEANvsP)

#PET
MEANvsPET <- WSfactorsLarge %>% ggplot(aes(PET, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("Average Annual PET, cm")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$PET), parse = TRUE)

ggsave("Plots/Mean/MEANvsPET.jpg", MEANvsPET)

#snow percentage
MEANvsSNOWpct <- WSfactorsLarge %>% ggplot(aes(SNOW_PCT_PRECIP, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("Snow as % of Total Precipitation")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$SNOW_PCT_PRECIP), parse = TRUE)

ggsave("Plots/Mean/MEANvsSNOWpct.jpg", MEANvsSNOWpct)

#basin compactness
MEANvsCOMPACT <- WSfactorsLarge %>% ggplot(aes(BAS_COMPACTNESS, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("Basin Compactness Index")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$BAS_COMPACTNESS), parse = TRUE)

ggsave("Plots/Mean/MEANvsCOMPACT.jpg", MEANvsCOMPACT)

#AWC
MEANvsAWC <- WSfactorsLarge %>% ggplot(aes(AWCAVE, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("Soil Available Water Capacity")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$AWCAVE), parse = TRUE)

ggsave("Plots/Mean/MEANvsAWC.jpg", MEANvsAWC)

#permeability
MEANvsPERMEABILITY <- WSfactorsLarge %>% ggplot(aes(PERMAVE, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("Average Permeability, in/hr")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$PERMAVE), parse = TRUE)

ggsave("Plots/Mean/MEANvsPERMEABILITY.jpg", MEANvsPERMEABILITY)

#soil depth
MEANvsDEPTH <- WSfactorsLarge %>% ggplot(aes(ROCKDEPAVE, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("Average Soil Depth, in")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$ROCKDEPAVE), parse = TRUE)

ggsave("Plots/Mean/MEANvsDEPTH.jpg", MEANvsDEPTH)

#clay content
MEANvsCLAY <- WSfactorsLarge %>% ggplot(aes(CLAYAVE, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("% Clay")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$CLAYAVE), parse = TRUE)

ggsave("Plots/Mean/MEANvsCLAY.jpg", MEANvsCLAY)

#sand content
MEANvsSAND <- WSfactorsLarge %>% ggplot(aes(SANDAVE, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("% Sand")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$SANDAVE), parse = TRUE)

ggsave("Plots/Mean/MEANvsSAND.jpg", MEANvsSAND)

#silt content
MEANvsSILT <- WSfactorsLarge %>% ggplot(aes(SILTAVE, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("% Silt")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$SILTAVE), parse = TRUE)

ggsave("Plots/Mean/MEANvsSILT.jpg", MEANvsSILT)

#average elevation
MEANvsELEV <- WSfactorsLarge %>% ggplot(aes(ELEV_MEAN_M_BASIN, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("Mean Elevation, m")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$ELEV_MEAN_M_BASIN), parse = TRUE)

ggsave("Plots/Mean/MEANvsELEV.jpg", MEANvsELEV)

#relief ratio
MEANvsRELIEF <- WSfactorsLarge %>% ggplot(aes(RRMEAN, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("Relief Ratio")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$RRMEAN), parse = TRUE)

ggsave("Plots/Mean/MEANvsRELIEF.jpg", MEANvsRELIEF)

#slope
MEANvsSLOPE <- WSfactorsLarge %>% ggplot(aes(SLOPE_PCT, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("Average % Slope")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$SLOPE_PCT), parse = TRUE)

ggsave("Plots/Mean/MEANvsSLOPE.jpg", MEANvsSLOPE)

#aspect
MEANvsASPECT <- WSfactorsLarge %>% ggplot(aes(ASPECT_DEGREES, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("Aspect, Degrees")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$ASPECT_DEGREES), parse = TRUE)

ggsave("Plots/Mean/MEANvsASPECT.jpg", MEANvsASPECT)

#developed
MEANvsDEV <- WSfactorsLarge %>% ggplot(aes(DEVNLCD06, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("% Developed Land")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$DEVNLCD06), parse = TRUE)

ggsave("Plots/Mean/MEANvsDEV.jpg", MEANvsDEV)

#forested
MEANvsFOREST <- WSfactorsLarge %>% ggplot(aes(FORESTNLCD06, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("% Forested Land")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$FORESTNLCD06), parse = TRUE)

ggsave("Plots/Mean/MEANvsFOREST.jpg", MEANvsFOREST)

#agriculture
MEANvsAG <- WSfactorsLarge %>% ggplot(aes(PLANTNLCD06, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("% Agricultural Land")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$PLANTNLCD06), parse = TRUE)

ggsave("Plots/Mean/MEANvsAG.jpg", MEANvsAG)

#surface water
MEANvsLAKES <- WSfactorsLarge %>% ggplot(aes(WATERNLCD06, Mean))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flow (mm/day)")+
  xlab("% Water Bodies")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Mean, WSfactorsLarge$WATERNLCD06), parse = TRUE)

ggsave("Plots/Mean/MEANvsLAKES.jpg", MEANvsLAKES)
```

Flow duration curve

```{r}
FDC <- QdatDV %>% ggplot(aes(x = P, y = Qmm_day, group = site_no, color = PROVINCE))+
  geom_line()+
  scale_y_log10()+
  xlab("% Time flow equalled or exceeded")+
  ylab("Q (mm/day)")

FDC
ggsave("Plots/FDC.jpg", FDC)



FDC_lows <- QdatDV %>% ggplot(aes(x = P, y = Qmm_day, group = site_no, color = PROVINCE))+
  geom_line()+
  xlim(90, 100)+
  ylim(0,1.2)+
  #scale_y_log10()+
  xlab("% Time flow equalled or exceeded")+
  ylab("Q (mm/day)")

FDC_lows
ggsave("Plots/FDC_lows.jpg", FDC_lows)



FDC_highs <- QdatDV %>% ggplot(aes(x = P, y = Qmm_day, group = site_no, color = PROVINCE))+
  geom_line()+
  xlim(0, 0.5)+
  #scale_y_log10()+
  xlab("% Time flow equalled or exceeded")+
  ylab("Q (mm/day)")

FDC_highs
ggsave("Plots/FDC_highs.jpg", FDC_highs)



FDC_short <- QdatDV %>% ggplot(aes(x = P, y = Qmm_day, group = site_no, color = PROVINCE))+
  geom_line()+
  ylim(0, 5)+
  #scale_y_log10()+
  xlab("% Time flow equalled or exceeded")+
  ylab("Q (mm/day)")

FDC_short
ggsave("Plots/FDC_short.jpg", FDC_short)
```

7Q10

```{r}
SevenQtenSF <- SevenQten %>% st_as_sf(sf_column_name = "geometry")

SevenQtenMap <- tm_shape(SevenQtenSF)+
  tm_symbols(col = "PearsonxQy", size = 0.2, style = "quantile", legend.hist = TRUE)+
  tm_layout(title = "7Q10", legend.outside = TRUE)+
tm_shape(us_states)+
  tm_borders()

SevenQtenMap
tmap_save(SevenQtenMap, "Plots/SevenQtenMap.jpg")

SevenQtenBox <- SevenQten %>% ggplot(aes(PROVINCE, PearsonxQy))+
  stat_boxplot()+
  ylab("7Q10 (mm/day)")+
  theme(axis.text.x = element_text(angle = 90))

SevenQtenBox
ggsave("Plots/SevenQtenBoxplot.jpg", SevenQtenBox)
```

Baseflow

```{r}
WSfactorsSF <- WSfactors %>% st_as_sf(sf_column_name = "geometry")

BFIvsPMap <- tm_shape(WSfactorsSF)+
  tm_symbols(col = "BFI_AVE", size = 0.2, style = "quantile", legend.hist = TRUE)+
  tm_layout(legend.outside = TRUE)+
tm_shape(Pmap)+
  tm_polygons(col = "PRECIPITAT")+
  tm_shape(us_states)+
  tm_borders()

BFIvsPMap
tmap_save(BFIMap, "Plots/BFIMap.jpg")

BFIBox <- WSfactors %>% ggplot(aes(PROVINCE, BFI_AVE))+
  stat_boxplot()+
  ylab("BFI")+
  theme(axis.text.x = element_text(angle = 90))

BFIBox
ggsave("Plots/BFIBoxplot.jpg", BFIBox)
```

BFI test

```{r}
BFItest <- QdatBaseflow %>% filter(site_no == "01052500")

BFItest %>% ggplot(aes(Date, Flow))+
  geom_line()+
  geom_line(aes(Date, bt, col = "red"))+
  ylim(0, 2000)+
  xlim(ymd("1981-01-01"), ymd("1982-01-01"))
```

Flashiness

```{r}
FlashinessMeanSF <- FlashinessMean %>% st_as_sf(sf_column_name = "geometry")

FlashinessMap <- tm_shape(FlashinessMeanSF)+
  tm_symbols(col = "Flashiness", size = 0.2, style = "quantile", legend.hist = TRUE)+
  tm_layout(legend.outside = TRUE)+
tm_shape(us_states)+
  tm_borders()

FlashinessMap
tmap_save(FlashinessMap, "Plots/FlashinessMap.jpg")

FlashinessBox <- FlashinessMean %>% ggplot(aes(PROVINCE, Flashiness))+
  stat_boxplot()+
  ylab("Flashiness Index")+
  theme(axis.text.x = element_text(angle = 90))

FlashinessBox
ggsave("Plots/FlashinessBoxplot.jpg", FlashinessBox)
```

Flashiness Change

```{r}
FlashinessChangeSF <- FlashinessChange %>% st_as_sf(sf_column_name = "geometry")

FlashinessChangeMap <- tm_shape(FlashinessChangeSF)+
  tm_symbols(col = "PercentChange", size = 0.2, style = "quantile", legend.hist = TRUE)+
  tm_layout(legend.outside = TRUE, title = "% Change in Flashiness, 1980s vs. 2000s")+
tm_shape(us_states)+
  tm_borders()

FlashinessChangeMap
tmap_save(FlashinessChangeMap, "Plots/FlashinessChangeMap.jpg")

FlashinessChangeBox <- FlashinessChange %>% ggplot(aes(PROVINCE, PercentChange))+
  stat_boxplot()+
  ylab("% Change in Flashiness Index, 1980s vs. 2000s")+
  theme(axis.text.x = element_text(angle = 90))

FlashinessChangeBox
ggsave("Plots/FlashinessChangeBoxplot.jpg", FlashinessChangeBox)
```

BFI vs watershed characteristics

```{r}
#using BFI_AVE in GAGESII (1971-2000)
WSfactorsLarge <- WSfactors %>% full_join(AppGagesSlim, by = "STAID")

WSfactorsLarge <- WSfactorsLarge %>% full_join(Soils, by = "STAID")

WSfactorsLarge <- WSfactorsLarge %>% full_join(Topography, by = "STAID")

WSfactorsLarge <- WSfactorsLarge %>% full_join(Landcover, by = "STAID")

#Dominant geology
BFIvsGEO <- WSfactorsLarge %>% ggplot(aes(GEOL_REEDBUSH_DOM, BFI_AVE))+
  stat_boxplot()+
  ylab("Average BFI")+
  xlab("Dominant Geology")

ggsave("Plots/BFI/BFIvsGEO.jpg", BFIvsGEO)

#topographic wetness index
BFIvsTWI <- WSfactorsLarge %>% ggplot(aes(TOPWET, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("Topographic Wetness Index")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$TOPWET), parse = TRUE)

ggsave("Plots/BFI/BFIvsTWI.jpg", BFIvsTWI)

#average annual precip
BFIvsP <- WSfactorsLarge %>% ggplot(aes(PPTAVG_BASIN, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("Average Annual Precipitation, cm")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$PPTAVG_BASIN), parse = TRUE)

ggsave("Plots/BFI/BFIvsP.jpg", BFIvsP)

#PET
BFIvsPET <- WSfactorsLarge %>% ggplot(aes(PET, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("Average Annual PET, cm")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$PET), parse = TRUE)

ggsave("Plots/BFI/BFIvsPET.jpg", BFIvsPET)

#snow percentage
BFIvsSNOWpct <- WSfactorsLarge %>% ggplot(aes(SNOW_PCT_PRECIP, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("Snow as % of Total Precipitation")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$SNOW_PCT_PRECIP), parse = TRUE)

ggsave("Plots/BFI/BFIvsSNOWpct.jpg", BFIvsSNOWpct)

#basin compactness
BFIvsCOMPACT <- WSfactorsLarge %>% ggplot(aes(BAS_COMPACTNESS, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("Basin Compactness Index")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$BAS_COMPACTNESS), parse = TRUE)

ggsave("Plots/BFI/BFIvsCOMPACT.jpg", BFIvsCOMPACT)

#AWC
BFIvsAWC <- WSfactorsLarge %>% ggplot(aes(AWCAVE, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("Soil Available Water Capacity")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$AWCAVE), parse = TRUE)

ggsave("Plots/BFI/BFIvsAWC.jpg", BFIvsAWC)

#permeability
BFIvsPERMEABILITY <- WSfactorsLarge %>% ggplot(aes(PERMAVE, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("Average Permeability, in/hr")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$PERMAVE), parse = TRUE)

ggsave("Plots/BFI/BFIvsPERMEABILITY.jpg", BFIvsPERMEABILITY)

#soil depth
BFIvsDEPTH <- WSfactorsLarge %>% ggplot(aes(ROCKDEPAVE, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("Average Soil Depth, in")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$ROCKDEPAVE), parse = TRUE)

ggsave("Plots/BFI/BFIvsDEPTH.jpg", BFIvsDEPTH)

#clay content
BFIvsCLAY <- WSfactorsLarge %>% ggplot(aes(CLAYAVE, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("% Clay")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$CLAYAVE), parse = TRUE)

ggsave("Plots/BFI/BFIvsCLAY.jpg", BFIvsCLAY)

#sand content
BFIvsSAND <- WSfactorsLarge %>% ggplot(aes(SANDAVE, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("% Sand")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$SANDAVE), parse = TRUE)

ggsave("Plots/BFI/BFIvsSAND.jpg", BFIvsSAND)

#silt content
BFIvsSILT <- WSfactorsLarge %>% ggplot(aes(SILTAVE, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("% Silt")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$SILTAVE), parse = TRUE)

ggsave("Plots/BFI/BFIvsSILT.jpg", BFIvsSILT)

#average elevation
BFIvsELEV <- WSfactorsLarge %>% ggplot(aes(ELEV_MEAN_M_BASIN, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("Mean Elevation, m")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$ELEV_MEAN_M_BASIN), parse = TRUE)

ggsave("Plots/BFI/BFIvsELEV.jpg", BFIvsELEV)

#relief ratio
BFIvsRELIEF <- WSfactorsLarge %>% ggplot(aes(RRMEAN, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("Relief Ratio")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$RRMEAN), parse = TRUE)

ggsave("Plots/BFI/BFIvsRELIEF.jpg", BFIvsRELIEF)

#slope
BFIvsSLOPE <- WSfactorsLarge %>% ggplot(aes(SLOPE_PCT, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("Average % Slope")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$SLOPE_PCT), parse = TRUE)

ggsave("Plots/BFI/BFIvsSLOPE.jpg", BFIvsSLOPE)

#aspect
BFIvsASPECT <- WSfactorsLarge %>% ggplot(aes(ASPECT_DEGREES, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("Aspect, Degrees")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$ASPECT_DEGREES), parse = TRUE)

ggsave("Plots/BFI/BFIvsASPECT.jpg", BFIvsASPECT)

#developed
BFIvsDEV <- WSfactorsLarge %>% ggplot(aes(DEVNLCD06, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("% Developed Land")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$DEVNLCD06), parse = TRUE)

ggsave("Plots/BFI/BFIvsDEV.jpg", BFIvsDEV)

#forested
BFIvsFOREST <- WSfactorsLarge %>% ggplot(aes(FORESTNLCD06, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("% Forested Land")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$FORESTNLCD06), parse = TRUE)

ggsave("Plots/BFI/BFIvsFOREST.jpg", BFIvsFOREST)

#agriculture
BFIvsAG <- WSfactorsLarge %>% ggplot(aes(PLANTNLCD06, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("% Agricultural Land")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$PLANTNLCD06), parse = TRUE)

ggsave("Plots/BFI/BFIvsAG.jpg", BFIvsAG)

#surface water
BFIvsLAKES <- WSfactorsLarge %>% ggplot(aes(WATERNLCD06, BFI_AVE))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average BFI")+
  xlab("% Water Bodies")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$BFI_AVE, WSfactorsLarge$WATERNLCD06), parse = TRUE)

ggsave("Plots/BFI/BFIvsLAKES.jpg", BFIvsLAKES)
```

Flashiness vs. watershed characteristics

```{r}

WSfactorsLarge <- WSfactorsLarge %>% inner_join(select(FlashinessMean, site_no, Flashiness), by = c("STAID" = "site_no"))

#Dominant geology
RBIvsGEO <- WSfactorsLarge %>% ggplot(aes(GEOL_REEDBUSH_DOM, Flashiness))+
  stat_boxplot()+
  ylab("Average Flashiness")+
  xlab("Dominant Geology")

ggsave("Plots/Flashiness/RBIvsGEO.jpg", RBIvsGEO)

#topographic wetness index
RBIvsTWI <- WSfactorsLarge %>% ggplot(aes(TOPWET, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("Topographic Wetness Index")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$TOPWET), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsTWI.jpg", RBIvsTWI)

#average annual precip
RBIvsP <- WSfactorsLarge %>% ggplot(aes(PPTAVG_BASIN, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("Average Annual Precipitation, cm")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$PPTAVG_BASIN), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsP.jpg", RBIvsP)

#PET
RBIvsPET <- WSfactorsLarge %>% ggplot(aes(PET, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("Average Annual PET, cm")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$PET), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsPET.jpg", RBIvsPET)

#snow percentage
RBIvsSNOWpct <- WSfactorsLarge %>% ggplot(aes(SNOW_PCT_PRECIP, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("Snow as % of Total Precipitation")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$SNOW_PCT_PRECIP), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsSNOWpct.jpg", RBIvsSNOWpct)

#basin compactness
RBIvsCOMPACT <- WSfactorsLarge %>% ggplot(aes(BAS_COMPACTNESS, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("Basin Compactness Index")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$BAS_COMPACTNESS), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsCOMPACT.jpg", RBIvsCOMPACT)

#AWC
RBIvsAWC <- WSfactorsLarge %>% ggplot(aes(AWCAVE, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("Soil Available Water Capacity")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$AWCAVE), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsAWC.jpg", RBIvsAWC)

#permeability
RBIvsPERMEABILITY <- WSfactorsLarge %>% ggplot(aes(PERMAVE, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("Average Permeability, in/hr")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$PERMAVE), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsPERMEABILITY.jpg", RBIvsPERMEABILITY)

#soil depth
RBIvsDEPTH <- WSfactorsLarge %>% ggplot(aes(ROCKDEPAVE, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("Average Soil Depth, in")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$ROCKDEPAVE), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsDEPTH.jpg", RBIvsDEPTH)

#clay content
RBIvsCLAY <- WSfactorsLarge %>% ggplot(aes(CLAYAVE, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("% Clay")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$CLAYAVE), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsCLAY.jpg", RBIvsCLAY)

#sand content
RBIvsSAND <- WSfactorsLarge %>% ggplot(aes(SANDAVE, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("% Sand")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$SANDAVE), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsSAND.jpg", RBIvsSAND)

#silt content
RBIvsSILT <- WSfactorsLarge %>% ggplot(aes(SILTAVE, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("% Silt")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$SILTAVE), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsSILT.jpg", RBIvsSILT)

#average elevation
RBIvsELEV <- WSfactorsLarge %>% ggplot(aes(ELEV_MEAN_M_BASIN, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("Mean Elevation, m")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$ELEV_MEAN_M_BASIN), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsELEV.jpg", RBIvsELEV)

#relief ratio
RBIvsRELIEF <- WSfactorsLarge %>% ggplot(aes(RRMEAN, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("Relief Ratio")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$RRMEAN), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsRELIEF.jpg", RBIvsRELIEF)

#slope
RBIvsSLOPE <- WSfactorsLarge %>% ggplot(aes(SLOPE_PCT, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("Average % Slope")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$SLOPE_PCT), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsSLOPE.jpg", RBIvsSLOPE)

#aspect
RBIvsASPECT <- WSfactorsLarge %>% ggplot(aes(ASPECT_DEGREES, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("Aspect, Degrees")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$ASPECT_DEGREES), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsASPECT.jpg", RBIvsASPECT)

#developed
RBIvsDEV <- WSfactorsLarge %>% ggplot(aes(DEVNLCD06, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("% Developed Land")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$DEVNLCD06), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsDEV.jpg", RBIvsDEV)

#forested
RBIvsFOREST <- WSfactorsLarge %>% ggplot(aes(FORESTNLCD06, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("% Forested Land")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$FORESTNLCD06), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsFOREST.jpg", RBIvsFOREST)

#agriculture
RBIvsAG <- WSfactorsLarge %>% ggplot(aes(PLANTNLCD06, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("% Agricultural Land")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$PLANTNLCD06), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsAG.jpg", RBIvsAG)

#surface water
RBIvsLAKES <- WSfactorsLarge %>% ggplot(aes(WATERNLCD06, Flashiness))+
  geom_point(aes(col = PROVINCE))+
  ylab("Average Flashiness")+
  xlab("% Water Bodies")+
  theme(aspect.ratio = 1)+
  geom_smooth(method = "lm", col = "black")+
  geom_text(x = -Inf, y = Inf, hjust = 0, vjust = 1, label = lm_eqn(WSfactorsLarge$Flashiness, WSfactorsLarge$WATERNLCD06), parse = TRUE)

ggsave("Plots/Flashiness/RBIvsLAKES.jpg", RBIvsLAKES)
```

Most influential characteristics

```{r}
WSfactorsLarge %>% ggplot(aes(PROVINCE, SANDAVE))+
  stat_boxplot()

WSfactorsLarge %>% ggplot(aes(PROVINCE, PPTAVG_BASIN))+
  stat_boxplot()

WSfactorsLarge %>% ggplot(aes(PROVINCE, ELEV_MEAN_M_BASIN))+
  stat_boxplot()

```
