---
title: "Read in"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dataRetrieval)
library(tidyverse)
#install.packages('conflicted')
library(conflicted)
```

## Daily means

```{r}
sitenos <- AppGages$STAID
parameterCd <- "00060" 
startDate <- "1981-01-01"  
endDate <- "2010-12-31"


#117 gages: 3 groups of 31
for(i in 1:93)
{
if(i == 1){
  QdatDV <- readNWISdv(sitenos[i], parameterCd, startDate, endDate)
}else{
   QdatDVnew <- readNWISdv(sitenos[i], parameterCd, startDate, endDate) 
  QdatDV <- rbind(QdatDVnew, QdatDV)
   }
}
```

Join to attribute table, calculate area-normalized flow in mm/day

```{r}
QdatDV <- QdatDV %>% renameNWISColumns()

write.csv(QdatDV, "QdatDV.csv")


QdatDV <- read_csv("QdatDV.csv")

conflict_prefer("select", "dplyr")

AppGagesSlim <- AppGages %>% 
  select(DIVISION, PROVINCE, SECTION, STAID, station_nm, DRAIN_SQKM, huc_cd, LAT_GAGE, LNG_GAGE, STATE, alt_va, geometry)

QdatDV <- inner_join(QdatDV, AppGagesSlim, by = c("site_no" = "STAID"))

#cfs to mm/day
QdatDV <- QdatDV %>% mutate(Qmm_day = 2.447 * Flow / DRAIN_SQKM)



AppGagesSlim <- AppGagesSlim %>% 
  filter(PROVINCE != "NEW ENGLAND" & PROVINCE != "ADIRONDACK" & SECTION != "SOUTHERN NEW YORK" & SECTION != "CATSKILL")
```

Baseflow

```{r}
# write.csv(QdatBaseflow, "QdatBaseflow.csv")
# 
# QdatBaseflow <- read_csv("QdatBaseflow.csv")
```

Watershed characteristics

```{r}
#All from GAGESII

Soils <- read_csv("Gages II Data/conterm_soils.txt") %>%
  filter(STAID %in% sitenos)

Landcover <- full_join(read_csv("Gages II Data/conterm_lc06_basin.txt"), read_csv("Gages II Data/conterm_lc06_rip800.txt"), by = "STAID") %>% 
  filter(STAID %in% sitenos)

Topography <- read_csv("Gages II Data/conterm_topo.txt") %>%
  filter(STAID %in% sitenos)

WSfactors <- full_join(read_csv("Gages II Data/conterm_geology.txt"), read_csv("Gages II Data/conterm_hydro.txt"), by = "STAID") %>%
  full_join(read_csv("Gages II Data/conterm_climate.txt"), by = "STAID") %>%
  full_join(read_csv("Gages II Data/conterm_basinid.txt"), by = "STAID") %>%
  filter(STAID %in% sitenos)
```
